import { TableColumn } from "react-data-table-component";

export interface OverviewDataRow {
  customerName: string;
  profession: string;
  email: string;
  dateJoined: string;
  id: number;
}

export const tableColumns: TableColumn<OverviewDataRow>[] = [
  {
    name: "customer name",
    selector: (row) => row.customerName,
  },
  {
    name: "profession",
    selector: (row) => row.profession,
  },
  {
    name: "email",
    selector: (row) => row.email,
  },
  {
    name: "date joined",
    selector: (row) => row.dateJoined,
  },
  {
    cell: (row) => <div>Hello {JSON.stringify(row.email)}</div>,
    button: true,
    width: "56px",
  },
];

export const tableCustomStyles = {
  rows: {
    style: {
      minHeight: "62px",
    },
  },
  headCells: {
    style: {
      fontSize: "14px",
      fontWeight: 500,
      textTransform: "uppercase" as "uppercase",
      color: "#71717A",
    },
  },
  cells: {
    style: {
      paddingTop: "18px",
      paddingBottom: "18px",
      fontSize: "14px",
      color: "#161616",
      fontWeight: 500,
    },
  },
};

export const TempTableData = [
  {
    id: 1,
    customerName: "Herbert Macaulay",
    profession: "Doctor",
    email: "herbert.macaulay@mail.com",
    dateJoined: "12/04/2024",
  },
  {
    id: 2,
    customerName: "Florence Nightingale",
    profession: "Nurse",
    email: "florence.nightingale@mail.com",
    dateJoined: "15/04/2024",
  },
  {
    id: 3,
    customerName: "Alexander Fleming",
    profession: "Pharmacist",
    email: "alexander.fleming@mail.com",
    dateJoined: "18/04/2024",
  },
  {
    id: 4,
    customerName: "Marie Curie",
    profession: "Physiotherapist",
    email: "marie.curie@mail.com",
    dateJoined: "20/04/2024",
  },
  {
    id: 5,
    customerName: "Sigmund Freud",
    profession: "Healthcare Assistant",
    email: "sigmund.freud@mail.com",
    dateJoined: "22/04/2024",
  },
  {
    id: 6,
    customerName: "Clara Barton",
    profession: "Nurse",
    email: "clara.barton@mail.com",
    dateJoined: "24/04/2024",
  },
  {
    id: 7,
    customerName: "Louis Pasteur",
    profession: "Doctor",
    email: "louis.pasteur@mail.com",
    dateJoined: "26/04/2024",
  },
  {
    id: 8,
    customerName: "Joseph Lister",
    profession: "Pharmacist",
    email: "joseph.lister@mail.com",
    dateJoined: "28/04/2024",
  },
  {
    id: 9,
    customerName: "Elizabeth Blackwell",
    profession: "Physiotherapist",
    email: "elizabeth.blackwell@mail.com",
    dateJoined: "30/04/2024",
  },
  {
    id: 10,
    customerName: "Edward Jenner",
    profession: "Doctor",
    email: "edward.jenner@mail.com",
    dateJoined: "02/05/2024",
  },
  {
    id: 11,
    customerName: "Jonas Salk",
    profession: "Healthcare Assistant",
    email: "jonas.salk@mail.com",
    dateJoined: "04/05/2024",
  },
  {
    id: 12,
    customerName: "Mary Seacole",
    profession: "Nurse",
    email: "mary.seacole@mail.com",
    dateJoined: "06/05/2024",
  },
  {
    id: 13,
    customerName: "Gregory Pincus",
    profession: "Pharmacist",
    email: "gregory.pincus@mail.com",
    dateJoined: "08/05/2024",
  },
  {
    id: 14,
    customerName: "Joseph Murray",
    profession: "Doctor",
    email: "joseph.murray@mail.com",
    dateJoined: "10/05/2024",
  },
  {
    id: 15,
    customerName: "Jane Cooke Wright",
    profession: "Physiotherapist",
    email: "jane.cooke@mail.com",
    dateJoined: "12/05/2024",
  },
  {
    id: 16,
    customerName: "Christiaan Barnard",
    profession: "Healthcare Assistant",
    email: "christiaan.barnard@mail.com",
    dateJoined: "14/05/2024",
  },
  {
    id: 17,
    customerName: "Virginia Apgar",
    profession: "Doctor",
    email: "virginia.apgar@mail.com",
    dateJoined: "16/05/2024",
  },
  {
    id: 18,
    customerName: "Rosalind Franklin",
    profession: "Physiotherapist",
    email: "rosalind.franklin@mail.com",
    dateJoined: "18/05/2024",
  },
  {
    id: 19,
    customerName: "Albert Sabin",
    profession: "Healthcare Assistant",
    email: "albert.sabin@mail.com",
    dateJoined: "20/05/2024",
  },
  {
    id: 20,
    customerName: "James Watson",
    profession: "Doctor",
    email: "james.watson@mail.com",
    dateJoined: "22/05/2024",
  },
  {
    id: 21,
    customerName: "Robert Koch",
    profession: "Pharmacist",
    email: "robert.koch@mail.com",
    dateJoined: "24/05/2024",
  },
  {
    id: 22,
    customerName: "Paul Ehrlich",
    profession: "Doctor",
    email: "paul.ehrlich@mail.com",
    dateJoined: "26/05/2024",
  },
  {
    id: 23,
    customerName: "Frederick Banting",
    profession: "Nurse",
    email: "frederick.banting@mail.com",
    dateJoined: "28/05/2024",
  },
  {
    id: 24,
    customerName: "Charles Best",
    profession: "Pharmacist",
    email: "charles.best@mail.com",
    dateJoined: "30/05/2024",
  },
  {
    id: 25,
    customerName: "Patrick Steptoe",
    profession: "Physiotherapist",
    email: "patrick.steptoe@mail.com",
    dateJoined: "01/06/2024",
  },
  {
    id: 26,
    customerName: "Walter Reed",
    profession: "Doctor",
    email: "walter.reed@mail.com",
    dateJoined: "03/06/2024",
  },
  {
    id: 27,
    customerName: "Christiaan Barnard",
    profession: "Nurse",
    email: "christiaan.barnard@mail.com",
    dateJoined: "05/06/2024",
  },
  {
    id: 28,
    customerName: "Elizabeth Garrett Anderson",
    profession: "Physiotherapist",
    email: "elizabeth.anderson@mail.com",
    dateJoined: "07/06/2024",
  },
  {
    id: 29,
    customerName: "Harold Varmus",
    profession: "Healthcare Assistant",
    email: "harold.varmus@mail.com",
    dateJoined: "09/06/2024",
  },
  {
    id: 30,
    customerName: "Anthony Fauci",
    profession: "Doctor",
    email: "anthony.fauci@mail.com",
    dateJoined: "11/06/2024",
  },
  {
    id: 31,
    customerName: "Frances Kelsey",
    profession: "Nurse",
    email: "frances.kelsey@mail.com",
    dateJoined: "13/06/2024",
  },
  {
    id: 32,
    customerName: "Alice Ball",
    profession: "Pharmacist",
    email: "alice.ball@mail.com",
    dateJoined: "15/06/2024",
  },
  {
    id: 33,
    customerName: "Charles Drew",
    profession: "Physiotherapist",
    email: "charles.drew@mail.com",
    dateJoined: "17/06/2024",
  },
  {
    id: 34,
    customerName: "Ruth Ella Moore",
    profession: "Healthcare Assistant",
    email: "ruth.moore@mail.com",
    dateJoined: "19/06/2024",
  },
  {
    id: 35,
    customerName: "Susan La Flesche",
    profession: "Doctor",
    email: "susan.laflesche@mail.com",
    dateJoined: "21/06/2024",
  },
  {
    id: 36,
    customerName: "George Papanicolaou",
    profession: "Nurse",
    email: "george.papanicolaou@mail.com",
    dateJoined: "23/06/2024",
  },
  {
    id: 37,
    customerName: "Dorothy Crowfoot Hodgkin",
    profession: "Pharmacist",
    email: "dorothy.hodgkin@mail.com",
    dateJoined: "25/06/2024",
  },
  {
    id: 38,
    customerName: "Joseph Goldberger",
    profession: "Physiotherapist",
    email: "joseph.goldberger@mail.com",
    dateJoined: "27/06/2024",
  },
  {
    id: 39,
    customerName: "William Harvey",
    profession: "Healthcare Assistant",
    email: "william.harvey@mail.com",
    dateJoined: "29/06/2024",
  },
  {
    id: 40,
    customerName: "Christian Doppler",
    profession: "Doctor",
    email: "christian.doppler@mail.com",
    dateJoined: "01/07/2024",
  },
  {
    id: 41,
    customerName: "René Laennec",
    profession: "Nurse",
    email: "rene.laennec@mail.com",
    dateJoined: "03/07/2024",
  },
  {
    id: 42,
    customerName: "Daniel Hale Williams",
    profession: "Pharmacist",
    email: "daniel.williams@mail.com",
    dateJoined: "05/07/2024",
  },
  {
    id: 43,
    customerName: "Vivien Thomas",
    profession: "Physiotherapist",
    email: "vivien.thomas@mail.com",
    dateJoined: "07/07/2024",
  },
  {
    id: 44,
    customerName: "William Osler",
    profession: "Healthcare Assistant",
    email: "william.osler@mail.com",
    dateJoined: "09/07/2024",
  },
  {
    id: 45,
    customerName: "Gertrude Elion",
    profession: "Doctor",
    email: "gertrude.elion@mail.com",
    dateJoined: "11/07/2024",
  },
  {
    id: 46,
    customerName: "Hippocrates",
    profession: "Nurse",
    email: "hippocrates@mail.com",
    dateJoined: "13/07/2024",
  },
  {
    id: 47,
    customerName: "Imhotep",
    profession: "Pharmacist",
    email: "imhotep@mail.com",
    dateJoined: "15/07/2024",
  },
  {
    id: 48,
    customerName: "Hildegard of Bingen",
    profession: "Physiotherapist",
    email: "hildegard.bingen@mail.com",
    dateJoined: "17/07/2024",
  },
  {
    id: 49,
    customerName: "Ambroise Paré",
    profession: "Healthcare Assistant",
    email: "ambroise.pare@mail.com",
    dateJoined: "19/07/2024",
  },
  {
    id: 50,
    customerName: "Ignaz Semmelweis",
    profession: "Doctor",
    email: "ignaz.semmelweis@mail.com",
    dateJoined: "21/07/2024",
  },
];
